DROP TABLE IF EXISTS destinations;

CREATE TABLE destinations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL,
    estimated_cost INTEGER NOT NULL,
    additional_info TEXT NOT NULL
);


